import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { SettingsService } from '../../services/settings.service';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.page.html',
  styleUrls: ['./settings.page.scss'],
})
export class SettingsPage implements OnInit {

  settingsOption = '0';
  primaryColor = '#00fa6c';
  primaryDarkColor = '#00fa6c';
  secondaryColor = '#E9ECE4';
  secondaryDarkColor = '#171C3A';
  accentColor = '#00fa6c';
  accentDarkColor = '#00fa6c';
  docDetectedColor = '#9653BF8A';
  submitBackgroundColor = '#00fa6c';
  submitBorderColor = '#00fa6c';
  submitFontColor = '#171c3a';
  docDetectStrokeColor = '#FFFFFFFF';
  dialogMessageColor = '#171c3a';
  dialogMessageDarkColor = '#FFFFFF';
  dialogRightButtonColor = '#171c3a';
  dialogRightButtonDarkColor = '#171c3a';
  dialogRightBackgroundColor = '#00fa6c';
  dialogRightBackgroundDarkColor = '#00fa6c';
  dialogLeftButtonColor = '#171c3a';
  dialogLeftButtonDarkColor = '#FFFFFF';
  toolbarIconsColor = '#171c3a';
  toolbarIconsDarkColor = '#FFFFFF';
  documentTypeColor = '#000000';

  hideSettings = {
    allowSubmitUndetectedDocsIsOn: true,
    afterScanCloseCameraIsOn: true,
    autoCaptureIsOn: false,
    autoCropBrowserIsOn: false,
    autoCropGalleryIsOn: false,
    autoDocDetectionAndCropIsOn: true,
    autoDeleteAfterProcessing: false,
    autoDeleteLocalResourcesAfterProcessing: true,
    autoLightDetectionIsOn: true,
    autoRotateIsOn: false,
    autoSkewCorrectionIsOn: false,
    autoSubmitDocumentOnCapture: false,
    autoTagSource: false,
    autoTagDeviceId: false,
    autoTagLensVersion: false,
    autoTagPlatform: false,
    backupDocsToGallery: true,
    barcodeExtractionIsOn: false,
    blurDetectionIsOn: true,
    boostModeIsOn: false,
    boundingBoxesIsOn: false,
    browseIsOn: true,
    cleanBorderIsOn: false,
    creditCardDetectCardNumber: true,
    creditCardDetectCardHolderName: true,
    creditCardDetectCardCVC: true,
    creditCardDetectCardDate: true,
    closeCameraOnSubmit: true,
    confidenceDetailsIsOn: false,
    checksBackIsOn: false,
    checksBackIsRequired: false,
    detectBlurResponseIsOn: false,
    dewarpingIsOn: false,
    dictateIsOn: true,
    emailCCIsOn: true,
    fraudDetectionIsOn: false,
    galleryIsOn: true,
    gpuIsOn: true,
    glareDetectionIsOn: true,
    isReimbursableDefault: false,
    isProduction: true,
    locationServicesIsOn: false,
    manualCropIsOn: true,
    moreMenuIsOn: true,
    moreSettingsMenuIsOn: true,
    multipleDocumentsIsOn: true,
    multiplePagesCaptureIsOn: true,
    noCompressOnWifi: false,
    parseAddressIsOn: false,
    rotateDocIsOn: true,
    returnStitchedPDF: false,
    saveLogsIsOn: true,
    shareLogsIsOn: false,
    stitchIsOn: true,
    showStitchCounterNumber: false,
    showDocumentTypes: false,
    showNoDocumentDetectedWarning: true,
    softBinarizationIsOn: false,
    switchCameraIsOn: false,
    webhookIsOn: false,
    zoomIsOn: true,
    documentTypes: true,
    anyDocumentType: true,
    tags: true,
    originalImageSize: true,
    submitButtonRadius: true,
    emailDomain: true,
    externalID: true,
    ocrRegex: true,
    ocrViewCornerRadius: true,
    ocrViewWidth: true,
    ocrViewHeight: true,
  };

  constructor(private route: ActivatedRoute, private veryfiSettings: SettingsService) { }

  ngOnInit() {
    this.settingsOption = this.route.snapshot.paramMap.get('option');
    switch (this.settingsOption) {
      case '0':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['receipt'];
        this.receiptSettings();
        break;
      case '1':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['long_receipt'];
        this.longReceiptSettings();
        break;
      case '2':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['check'];
        this.checksSettings();
        break;
      case '3':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['credit_card'];
        this.creditCardsSettings();
        break;
      case '4':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['business_card'];
        this.businessCardSettings();
        break;
      case '5':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['code'];
        this.ocrSettings();
        break;
      case '6':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['w2'];
        this.w2Settings();
        break;
      case '7':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['w9'];
        this.w9Settings();
        break;
      case '8':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['bank_statements'];
        this.bankStatementSetings();
        break;
      case '9':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['barcodes'];
        this.barcodeSettings();
        break;
      case '10':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['insurance_card'];
        this.insuranceSettings();
        break;
      case '11':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['passport'];
        this.passportSettings();
        break;
      case '12':
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['driver_license'];
        this.driverLicenseSettings();
        break;
      default:
        this.veryfiSettings.veryfiLensSettings.documentTypes = ['receipt'];
        this.receiptSettings();
    }
  }

  receiptSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= true;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  longReceiptSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= true;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  checksSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= false;
    this.hideSettings.afterScanCloseCameraIsOn= false;
    this.hideSettings.autoCaptureIsOn= false;
    this.hideSettings.autoCropBrowserIsOn= false;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= false;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= false;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= false;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= false;
    this.hideSettings.cleanBorderIsOn= false;
    this.hideSettings.creditCardDetectCardNumber= false;
    this.hideSettings.creditCardDetectCardHolderName= false;
    this.hideSettings.creditCardDetectCardCVC= false;
    this.hideSettings.creditCardDetectCardDate= false;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= true;
    this.hideSettings.checksBackIsRequired= true;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= false;
    this.hideSettings.dictateIsOn= false;
    this.hideSettings.emailCCIsOn= false;
    this.hideSettings.fraudDetectionIsOn= false;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= false;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= false;
    this.hideSettings.manualCropIsOn= false;
    this.hideSettings.moreMenuIsOn= false;
    this.hideSettings.moreSettingsMenuIsOn= false;
    this.hideSettings.multipleDocumentsIsOn= false;
    this.hideSettings.multiplePagesCaptureIsOn= false;
    this.hideSettings.noCompressOnWifi= false;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= false;
    this.hideSettings.shareLogsIsOn= false;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= false;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= false;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= false;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= false;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= false;
    this.hideSettings.originalImageSize= false;
    this.hideSettings.submitButtonRadius= false;
    this.hideSettings.emailDomain= false;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  creditCardsSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= false;
    this.hideSettings.afterScanCloseCameraIsOn= false;
    this.hideSettings.autoCaptureIsOn= false;
    this.hideSettings.autoCropBrowserIsOn= false;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= false;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= false;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= false;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= false;
    this.hideSettings.cleanBorderIsOn= false;
    this.hideSettings.creditCardDetectCardNumber= false;
    this.hideSettings.creditCardDetectCardHolderName= false;
    this.hideSettings.creditCardDetectCardCVC= false;
    this.hideSettings.creditCardDetectCardDate= false;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= true;
    this.hideSettings.checksBackIsRequired= true;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= false;
    this.hideSettings.dictateIsOn= false;
    this.hideSettings.emailCCIsOn= false;
    this.hideSettings.fraudDetectionIsOn= false;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= false;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= false;
    this.hideSettings.manualCropIsOn= false;
    this.hideSettings.moreMenuIsOn= false;
    this.hideSettings.moreSettingsMenuIsOn= false;
    this.hideSettings.multipleDocumentsIsOn= false;
    this.hideSettings.multiplePagesCaptureIsOn= false;
    this.hideSettings.noCompressOnWifi= false;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= false;
    this.hideSettings.saveLogsIsOn= false;
    this.hideSettings.shareLogsIsOn= false;
    this.hideSettings.stitchIsOn= false;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= false;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= false;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= false;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= false;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= false;
    this.hideSettings.originalImageSize= false;
    this.hideSettings.submitButtonRadius= false;
    this.hideSettings.emailDomain= false;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  businessCardSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= false;
    this.hideSettings.afterScanCloseCameraIsOn= false;
    this.hideSettings.autoCaptureIsOn= false;
    this.hideSettings.autoCropBrowserIsOn= false;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= false;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= false;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= false;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= false;
    this.hideSettings.cleanBorderIsOn= false;
    this.hideSettings.creditCardDetectCardNumber= false;
    this.hideSettings.creditCardDetectCardHolderName= false;
    this.hideSettings.creditCardDetectCardCVC= false;
    this.hideSettings.creditCardDetectCardDate= false;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= true;
    this.hideSettings.checksBackIsRequired= true;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= false;
    this.hideSettings.dictateIsOn= false;
    this.hideSettings.emailCCIsOn= false;
    this.hideSettings.fraudDetectionIsOn= false;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= false;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= false;
    this.hideSettings.manualCropIsOn= false;
    this.hideSettings.moreMenuIsOn= false;
    this.hideSettings.moreSettingsMenuIsOn= false;
    this.hideSettings.multipleDocumentsIsOn= false;
    this.hideSettings.multiplePagesCaptureIsOn= false;
    this.hideSettings.noCompressOnWifi= false;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= false;
    this.hideSettings.saveLogsIsOn= false;
    this.hideSettings.shareLogsIsOn= false;
    this.hideSettings.stitchIsOn= false;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= false;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= false;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= false;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= false;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= false;
    this.hideSettings.originalImageSize= false;
    this.hideSettings.submitButtonRadius= false;
    this.hideSettings.emailDomain= false;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  ocrSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= false;
    this.hideSettings.afterScanCloseCameraIsOn= false;
    this.hideSettings.autoCaptureIsOn= false;
    this.hideSettings.autoCropBrowserIsOn= false;
    this.hideSettings.autoCropGalleryIsOn= false;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= false;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= false;
    this.hideSettings.autoLightDetectionIsOn= false;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= false;
    this.hideSettings.autoSubmitDocumentOnCapture= false;
    this.hideSettings.autoTagSource= false;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= false;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= false;
    this.hideSettings.boostModeIsOn= false;
    this.hideSettings.boundingBoxesIsOn= false;
    this.hideSettings.browseIsOn= false;
    this.hideSettings.cleanBorderIsOn= false;
    this.hideSettings.creditCardDetectCardNumber= false;
    this.hideSettings.creditCardDetectCardHolderName= false;
    this.hideSettings.creditCardDetectCardCVC= false;
    this.hideSettings.creditCardDetectCardDate= false;
    this.hideSettings.closeCameraOnSubmit= false;
    this.hideSettings.confidenceDetailsIsOn= false;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= false;
    this.hideSettings.dewarpingIsOn= false;
    this.hideSettings.dictateIsOn= false;
    this.hideSettings.emailCCIsOn= false;
    this.hideSettings.fraudDetectionIsOn= false;
    this.hideSettings.galleryIsOn= false;
    this.hideSettings.gpuIsOn= false;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= false;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= false;
    this.hideSettings.manualCropIsOn= false;
    this.hideSettings.moreMenuIsOn= false;
    this.hideSettings.moreSettingsMenuIsOn= false;
    this.hideSettings.multipleDocumentsIsOn= false;
    this.hideSettings.multiplePagesCaptureIsOn= false;
    this.hideSettings.noCompressOnWifi= false;
    this.hideSettings.parseAddressIsOn= false;
    this.hideSettings.rotateDocIsOn= false;
    this.hideSettings.returnStitchedPDF= false;
    this.hideSettings.saveLogsIsOn= false;
    this.hideSettings.shareLogsIsOn= false;
    this.hideSettings.stitchIsOn= false;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= false;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= false;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= false;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= false;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= false;
    this.hideSettings.originalImageSize= false;
    this.hideSettings.submitButtonRadius= false;
    this.hideSettings.emailDomain= false;
    this.hideSettings.externalID= false;
    this.hideSettings.ocrRegex= true;
    this.hideSettings.ocrViewCornerRadius= true;
    this.hideSettings.ocrViewWidth= true;
    this.hideSettings.ocrViewHeight= true;
  }

  w2Settings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= true;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  w9Settings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= true;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  bankStatementSetings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  barcodeSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= true;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  insuranceSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  passportSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  driverLicenseSettings() {
    this.hideSettings.allowSubmitUndetectedDocsIsOn= true;
    this.hideSettings.afterScanCloseCameraIsOn= true;
    this.hideSettings.autoCaptureIsOn= true;
    this.hideSettings.autoCropBrowserIsOn= true;
    this.hideSettings.autoCropGalleryIsOn= true;
    this.hideSettings.autoDocDetectionAndCropIsOn= true;
    this.hideSettings.autoDeleteAfterProcessing= true;
    this.hideSettings.autoDeleteLocalResourcesAfterProcessing= true;
    this.hideSettings.autoLightDetectionIsOn= true;
    this.hideSettings.autoRotateIsOn= true;
    this.hideSettings.autoSkewCorrectionIsOn= true;
    this.hideSettings.autoSubmitDocumentOnCapture= true;
    this.hideSettings.autoTagSource= true;
    this.hideSettings.autoTagDeviceId= true;
    this.hideSettings.autoTagLensVersion= true;
    this.hideSettings.autoTagPlatform= true;
    this.hideSettings.backupDocsToGallery= true;
    this.hideSettings.barcodeExtractionIsOn= false;
    this.hideSettings.blurDetectionIsOn= true;
    this.hideSettings.boostModeIsOn= true;
    this.hideSettings.boundingBoxesIsOn= true;
    this.hideSettings.browseIsOn= true;
    this.hideSettings.cleanBorderIsOn= true;
    this.hideSettings.creditCardDetectCardNumber= true;
    this.hideSettings.creditCardDetectCardHolderName= true;
    this.hideSettings.creditCardDetectCardCVC= true;
    this.hideSettings.creditCardDetectCardDate= true;
    this.hideSettings.closeCameraOnSubmit= true;
    this.hideSettings.confidenceDetailsIsOn= true;
    this.hideSettings.checksBackIsOn= false;
    this.hideSettings.checksBackIsRequired= false;
    this.hideSettings.detectBlurResponseIsOn= true;
    this.hideSettings.dewarpingIsOn= true;
    this.hideSettings.dictateIsOn= true;
    this.hideSettings.emailCCIsOn= true;
    this.hideSettings.fraudDetectionIsOn= true;
    this.hideSettings.galleryIsOn= true;
    this.hideSettings.gpuIsOn= true;
    this.hideSettings.glareDetectionIsOn= true;
    this.hideSettings.isReimbursableDefault= true;
    this.hideSettings.isProduction= true;
    this.hideSettings.locationServicesIsOn= true;
    this.hideSettings.manualCropIsOn= true;
    this.hideSettings.moreMenuIsOn= true;
    this.hideSettings.moreSettingsMenuIsOn= true;
    this.hideSettings.multipleDocumentsIsOn= true;
    this.hideSettings.multiplePagesCaptureIsOn= true;
    this.hideSettings.noCompressOnWifi= true;
    this.hideSettings.parseAddressIsOn= true;
    this.hideSettings.rotateDocIsOn= true;
    this.hideSettings.returnStitchedPDF= true;
    this.hideSettings.saveLogsIsOn= true;
    this.hideSettings.shareLogsIsOn= true;
    this.hideSettings.stitchIsOn= true;
    this.hideSettings.showStitchCounterNumber= true;
    this.hideSettings.showDocumentTypes= true;
    this.hideSettings.showNoDocumentDetectedWarning= true;
    this.hideSettings.softBinarizationIsOn= true;
    this.hideSettings.switchCameraIsOn= true;
    this.hideSettings.webhookIsOn= true;
    this.hideSettings.zoomIsOn= true;
    this.hideSettings.documentTypes= true;
    this.hideSettings.anyDocumentType= true;
    this.hideSettings.tags= true;
    this.hideSettings.originalImageSize= true;
    this.hideSettings.submitButtonRadius= true;
    this.hideSettings.emailDomain= true;
    this.hideSettings.externalID= true;
    this.hideSettings.ocrRegex= false;
    this.hideSettings.ocrViewCornerRadius= false;
    this.hideSettings.ocrViewWidth= false;
    this.hideSettings.ocrViewHeight= false;
  }

  resetSettings() {
    this.veryfiSettings.resetVeryfiLensSettings();
  }
}
