import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class SettingsService {

  public veryfiLensSettings = {
    allowSubmitUndetectedDocsIsOn: true,
    afterScanCloseCameraIsOn: true,
    autoCaptureIsOn: false,
    autoCropBrowserIsOn: false,
    autoCropGalleryIsOn: false,
    autoDocDetectionAndCropIsOn: true,
    autoDeleteAfterProcessing: false,
    autoDeleteLocalResourcesAfterProcessing: true,
    autoLightDetectionIsOn: true,
    autoRotateIsOn: false,
    autoSkewCorrectionIsOn: false,
    autoSubmitDocumentOnCapture: false,
    autoTagSource: false,
    autoTagDeviceId: false,
    autoTagLensVersion: false,
    autoTagPlatform: false,
    backupDocsToGallery: true,
    barcodeExtractionIsOn: false,
    blurDetectionIsOn: true,
    boostModeIsOn: false,
    boundingBoxesIsOn: false,
    browseIsOn: true,
    cleanBorderIsOn: false,
    creditCardDetectCardNumber: true,
    creditCardDetectCardHolderName: true,
    creditCardDetectCardCVC: true,
    creditCardDetectCardDate: true,
    closeCameraOnSubmit: true,
    confidenceDetailsIsOn: false,
    checksBackIsOn: false,
    checksBackIsRequired: false,
    detectBlurResponseIsOn: false,
    dewarpingIsOn: false,
    dictateIsOn: true,
    emailCCIsOn: true,
    fraudDetectionIsOn: false,
    galleryIsOn: true,
    gpuIsOn: true,
    glareDetectionIsOn: true,
    isReimbursableDefault: false,
    isProduction: true,
    locationServicesIsOn: false,
    manualCropIsOn: true,
    moreMenuIsOn: true,
    moreSettingsMenuIsOn: true,
    multipleDocumentsIsOn: true,
    multiplePagesCaptureIsOn: true,
    noCompressOnWifi: false,
    parseAddressIsOn: false,
    rotateDocIsOn: true,
    returnStitchedPDF: false,
    saveLogsIsOn: true,
    shareLogsIsOn: false,
    stitchIsOn: true,
    showStitchCounterNumber: false,
    showDocumentTypes: false,
    showNoDocumentDetectedWarning: true,
    softBinarizationIsOn: false,
    switchCameraIsOn: false,
    webhookIsOn: false,
    zoomIsOn: true,
    documentTypes: ['receipt'],
    anyDocumentType: 'None',
    tags: ['N/A'],
    originalImageSize: '2.5',
    submitButtonRadius: '5',
    emailDomain: 'veryfi.cc',
    externalID: 'N/A',
  };

  private defaultVeryfiLensSettings = {
    allowSubmitUndetectedDocsIsOn: true,
    afterScanCloseCameraIsOn: true,
    autoCaptureIsOn: false,
    autoCropBrowserIsOn: false,
    autoCropGalleryIsOn: false,
    autoDocDetectionAndCropIsOn: true,
    autoDeleteAfterProcessing: false,
    autoDeleteLocalResourcesAfterProcessing: true,
    autoLightDetectionIsOn: true,
    autoRotateIsOn: false,
    autoSkewCorrectionIsOn: false,
    autoSubmitDocumentOnCapture: false,
    autoTagSource: false,
    autoTagDeviceId: false,
    autoTagLensVersion: false,
    autoTagPlatform: false,
    backupDocsToGallery: true,
    barcodeExtractionIsOn: false,
    blurDetectionIsOn: true,
    boostModeIsOn: false,
    boundingBoxesIsOn: false,
    browseIsOn: true,
    cleanBorderIsOn: false,
    creditCardDetectCardNumber: true,
    creditCardDetectCardHolderName: true,
    creditCardDetectCardCVC: true,
    creditCardDetectCardDate: true,
    closeCameraOnSubmit: true,
    confidenceDetailsIsOn: false,
    checksBackIsOn: false,
    checksBackIsRequired: false,
    detectBlurResponseIsOn: false,
    dewarpingIsOn: false,
    dictateIsOn: true,
    emailCCIsOn: true,
    fraudDetectionIsOn: false,
    galleryIsOn: true,
    gpuIsOn: true,
    glareDetectionIsOn: true,
    isReimbursableDefault: false,
    isProduction: true,
    locationServicesIsOn: false,
    manualCropIsOn: true,
    moreMenuIsOn: true,
    moreSettingsMenuIsOn: true,
    multipleDocumentsIsOn: true,
    multiplePagesCaptureIsOn: true,
    noCompressOnWifi: false,
    parseAddressIsOn: false,
    rotateDocIsOn: true,
    returnStitchedPDF: false,
    saveLogsIsOn: true,
    shareLogsIsOn: false,
    stitchIsOn: true,
    showStitchCounterNumber: false,
    showDocumentTypes: false,
    showNoDocumentDetectedWarning: true,
    softBinarizationIsOn: false,
    switchCameraIsOn: false,
    webhookIsOn: false,
    zoomIsOn: true,
    documentTypes: ['receipt'],
    anyDocumentType: 'None',
    tags: ['N/A'],
    originalImageSize: '2.5',
    submitButtonRadius: '5',
    emailDomain: 'veryfi.cc',
    externalID: 'N/A',
  };

  constructor() { }

  public resetVeryfiLensSettings() {
    this.veryfiLensSettings = JSON.parse(JSON.stringify(this.defaultVeryfiLensSettings));
  }
}
